# Generated by Django 3.2.7 on 2021-09-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neigbouhood', '0003_auto_20210924_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bussinessclass',
            old_name='user',
            new_name='owner',
        ),
    ]
