# Generated by Django 3.2.7 on 2021-09-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neigbouhood', '0007_rename_userp_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
