# Generated by Django 3.2.7 on 2021-09-25 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neigbouhood', '0008_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='location',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='neigbouhood.location'),
        ),
        migrations.AddField(
            model_name='news',
            name='neiba',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='neigbouhood.neigbourhood'),
        ),
    ]
